services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017"  
    restart: always

  # Go Application Service
  app:
    build: .  # Specify the build context directory here
    container_name: my-go-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    restart: always

volumes:
  mongo-data:
    driver: local
